import React from "react";
import "../styles/project-grid.css";

import Sketch from "../p5/sketchTwo";
import ProjectCard from "./ProjectCard";
import ProjectInfo from "./ProjectInfo";
import {
  SiJavascript,
  SiMongodb,
  SiFirebase,
  SiNodedotjs,
  SiReact,
  SiExpo,
  SiPostgresql,
  SiExpress,
} from "react-icons/si";

import { FaHammer } from "react-icons/fa";

function Projects() {
  return (
    <div id="projects">
      <h2>Projects</h2>
      <section className="grid-container">
        <div className="grid-card">
          <ProjectCard
            title="Mushroom Finder App"
            url="https://images.pexels.com/photos/6034382/pexels-photo-6034382.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
          />
          <ProjectInfo
            link="/mushi-app"
            img={require("../images/mushi.png")}
            description="End to end mobile app project designed to help users find and identify wild mushrooms based on data generated by the user base. A colaborative project created during my time at Northcoders boot camp."
          >
            <SiJavascript />
            <SiNodedotjs />
            <SiReact />
            <SiExpo />
            <SiMongodb />
            <SiFirebase />
          </ProjectInfo>
        </div>
        <div className="grid-card sketch-card">
          <Sketch t={0} />
        </div>
        <div className="grid-card">
          <ProjectCard
            title="Game Review Site"
            url="https://images.pexels.com/photos/8762806/pexels-photo-8762806.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
          />
          <ProjectInfo
            link="/game-review-app"
            img={require("../images/bgb.png")}
            description="Full stack review site project that allows users to submit reviews of their favorite boadrgames, as well as comment and vote on reviews left by other users."
          >
            <SiJavascript />
            <SiNodedotjs />
            <SiReact />
            <SiPostgresql />
            <SiExpress />
          </ProjectInfo>
        </div>
        <div className="grid-card two-tall sketch-card">
          <Sketch t={20} />
        </div>
        <div className="grid-card two-wide two-tall">
          <ProjectCard title="Code Art" url={require("../images/plot.jpg")} />
          <ProjectInfo
            link="/code-art"
            img={require("../images/plotter.png")}
          ></ProjectInfo>
        </div>
        <div className="grid-card">
          <ProjectCard
            title="Beer Recipie Frontend"
            url="https://images.pexels.com/photos/1267700/pexels-photo-1267700.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
          />
          <ProjectInfo
            link="/brewdog-frontend"
            img={require("../images/beer-screenshot.png")}
            description="A single page Rect app, front end for Brewdogs free to use 'Punk API'"
          >
            <SiJavascript />
            <SiNodedotjs />
            <SiReact />
          </ProjectInfo>
        </div>
        <div className="grid-card sketch-card">
          <Sketch t={10} />
        </div>
        <div className="grid-card">
          <ProjectCard
            title="Other Projects"
            url={require("../images/workbench.jpg")}
          />
          <ProjectInfo>
            <FaHammer />
          </ProjectInfo>
        </div>
      </section>
    </div>
  );
}

export default Projects;
