import React from "react";
import "../styles/project-grid.css";
import Sketch from "../p5/sketchTwo";
import ProjectCard from "./ProjectCard";
import ProjectInfo from "./ProjectInfo";
import {
  SiGithub,
  SiInstagram,
  SiLinkedin,
  SiJavascript,
  SiMongodb,
  SiFirebase,
  SiNodedotjs,
  SiReact,
  SiExpo,
  SiPostgresql,
  SiExpress,
} from "react-icons/si";

function Projects() {
  return (
    <div id="projects">
      <section className="grid-container">
        <div className="grid-card">
          <ProjectCard
            title="Mushroom Finder App"
            url="https://images.pexels.com/photos/6034382/pexels-photo-6034382.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
          />
          <ProjectInfo
            link="/mushi-app"
            description="End to end mobile app project designed to help users find and identify wild mushrooms based on data generated by the user base. A colaborative project created during my time at Northcoders boot camp."
          >
            <SiJavascript />
            <SiNodedotjs />
            <SiReact />
            <SiExpo />
            <SiMongodb />
            <SiFirebase />
          </ProjectInfo>
        </div>

        <div className="grid-card">
          <ProjectCard
            title="Game Review Site"
            url="https://images.pexels.com/photos/8762806/pexels-photo-8762806.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
          />
          <ProjectInfo
            link="/game-review-app"
            description="Full stack review site project that allows users to submit reviews of their favorite boadrgames, as well as comment and vote on reviews left by other users."
          >
            <SiJavascript />
            <SiNodedotjs />
            <SiReact />
            <SiPostgresql />
            <SiExpress />
          </ProjectInfo>
        </div>

        <div className="grid-card ">
          <ProjectCard
            title="Code Art"
            url={"https://i.ibb.co/4TqCbkq/plot.jpg"}
          />
          <ProjectInfo
            link="/code-art"
            description="Code 'setches' made using P5.js, a 2D Javascript graphics library. I found this a to be a usefull tool while learning to code. I took some of the outputs and turned them into physical artworks using a pen plotter. "
          ></ProjectInfo>
        </div>
        <div className="grid-card">
          <ProjectCard
            title="Beer Recipie Frontend"
            url="https://images.pexels.com/photos/1267700/pexels-photo-1267700.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
          />
          <ProjectInfo
            link="/brewdog-frontend"
            description="A single page Rect app, front end for Brewdogs free to use 'Punk API'. The app allows users to search and sort the recipie catalouge, recipies can be added to a compare list and more detailed info can be viewed by selecting any of the recipies. "
          >
            <SiJavascript />
            <SiNodedotjs />
            <SiReact />
          </ProjectInfo>
        </div>

        <div className="grid-card">
          <ProjectCard
            title="Other Projects"
            url={"https://i.ibb.co/jyPHPkM/workbench.jpg"}
          />
          <ProjectInfo
            description="I have done a number of microcontroller / IOT projects in the past, before I had a propper apriciation of good documentation... More comming soon!!!"
            button="disabled"
          ></ProjectInfo>
        </div>
        <div className="sketch-card">
          <Sketch t={20} />
        </div>
      </section>

      <div className="social-icons">
        <a href="https://github.com/FisherTom">
          <SiGithub size={40} />
        </a>
        <a href="https://www.linkedin.com/in/thomas-fisher-098ab496/">
          <SiLinkedin size={40} />
        </a>
        <a href="https://www.instagram.com/end.shape/">
          <SiInstagram size={40} />
        </a>
      </div>
    </div>
  );
}

export default Projects;
